### ISSUE TITLE
geocode error

### ISSUE THREAD

**Issue by JulianNorton** [willnap/atmosphere#2]
https://atmosphere-10kapart2016.azurewebsites.net/
I noticed you had some geocode errors on Azure, for [wxkb.io](http://wxkb.io) we solved it this way:

https://github.com/JulianNorton/weather-10kb/commit/73ed8d3a1b80349eef484ddd2483638b32c878d4

Hope this helps!

I really like how you did your cookie units.

**Comment by willnap** [comment]
@JulianNorton Thanks for your help! The error turned out to be an over quota problem. It's fixed now.
